-- 테이블 삭제
--DROP TABLE DELIVERY CASCADE CONSTRAINTS;
--DROP TABLE ORDER_TABLE CASCADE CONSTRAINTS;
--DROP TABLE PRODUCT CASCADE CONSTRAINTS;
--DROP TABLE REVIEW CASCADE CONSTRAINTS;
--DROP TABLE CATEGORY CASCADE CONSTRAINTS;
--DROP TABLE PAY_BANK CASCADE CONSTRAINTS;
--DROP TABLE PAY_CARD CASCADE CONSTRAINTS;
--DROP TABLE PAYMENT_PLAN CASCADE CONSTRAINTS;
--DROP TABLE ANNOUNCEMENT CASCADE CONSTRAINTS;
--DROP TABLE QA CASCADE CONSTRAINTS;
--DROP TABLE FAQ CASCADE CONSTRAINTS;
--DROP TABLE BOARD CASCADE CONSTRAINTS;
--DROP TABLE AUTHORITY CASCADE CONSTRAINTS;
--DROP TABLE MEMBER CASCADE CONSTRAINTS;
--DROP TABLE CPU CASCADE CONSTRAINTS;
--DROP TABLE POWER CASCADE CONSTRAINTS;
--DROP TABLE "CASE" CASCADE CONSTRAINTS;
--DROP TABLE SSD CASCADE CONSTRAINTS;
--DROP TABLE HDD CASCADE CONSTRAINTS;
--DROP TABLE GRAPHIC_CARD CASCADE CONSTRAINTS;
--DROP TABLE RAM CASCADE CONSTRAINTS;
--DROP TABLE MAINBOARD CASCADE CONSTRAINTS;
--DROP TABLE COOLER CASCADE CONSTRAINTS;

-- SEQUENCE 삭제
--DROP SEQUENCE SEQ_DELEVERY;
--DROP SEQUENCE SEQ_ORDER_TABLE;
--DROP SEQUENCE SEQ_PRODUCT;
--DROP SEQUENCE SEQ_CATEGORY;
--DROP SEQUENCE SEQ_PAYBANK;
--DROP SEQUENCE SEQ_PAYCARD;
--DROP SEQUENCE SEQ_PAYMENT_PLAN;
--DROP SEQUENCE SEQ_ANNOUNCEMENT;
--DROP SEQUENCE SEQ_QA;
--DROP SEQUENCE SEQ_FAQ;
--DROP SEQUENCE SEQ_BOARD;
--DROP SEQUENCE SEQ_MEMBER;
--DROP SEQUENCE SEQ_CPU;
--DROP SEQUENCE SEQ_REVIEW;

-- 데이터베이스 정리
COMMIT;

-- Authority Table
CREATE TABLE "AUTHORITY" (
    "AUTH_ID" NUMBER PRIMARY KEY,
    "AUTH_NAME" VARCHAR2(100) NOT NULL,
    "AUTH_ROLE" VARCHAR2(100) NOT NULL
);

-- Member Table
CREATE TABLE "MEMBER" (
    "USER_ID" VARCHAR2(30) PRIMARY KEY,  -- 대소문자 구분
    "AUTH_ID" NUMBER NOT NULL,           -- Authority identifier
    "PASSWORD" VARCHAR2(30) NOT NULL,    -- User password
    "USERNAME" VARCHAR2(30) NOT NULL,    -- User name
    "GENDER" CHAR(1) NOT NULL CHECK ("GENDER" IN ('F', 'M')), -- Gender constraint
    "EMAIL" VARCHAR2(100) NOT NULL,      -- Email address
    "PHONE" VARCHAR2(30),                -- Phone number
    "REGISTER_DATE" DATE DEFAULT SYSDATE, -- Registration date
    "LAST_UPDATE" DATE DEFAULT SYSDATE,  -- Last update timestamp
    "MEMBER_STATUS" CHAR(1) DEFAULT 'Y' NOT NULL CHECK ("MEMBER_STATUS" IN ('Y', 'N')), -- Membership status constraint
    FOREIGN KEY ("AUTH_ID") REFERENCES "AUTHORITY"("AUTH_ID") -- Foreign key reference
);
CREATE SEQUENCE SEQ_MEMBER NOCACHE;

-- Board Table
CREATE TABLE "BOARD" (
    "BOARD_ID" NUMBER PRIMARY KEY,
    "USER_ID" VARCHAR2(30) NOT NULL,
    "AUTH_ID" NUMBER NOT NULL,
    "BOARD_TYPE" VARCHAR2(30) NOT NULL,
    FOREIGN KEY ("USER_ID") REFERENCES "MEMBER"("USER_ID"),
    FOREIGN KEY ("AUTH_ID") REFERENCES "AUTHORITY"("AUTH_ID")
);
CREATE SEQUENCE SEQ_BOARD NOCACHE;

DROP SEQUENCE SEQ_ANNOUNCEMENT;
DROP SEQUENCE SEQ_QA;
DROP SEQUENCE SEQ_FAQ;
DROP TABLE "ANNOUNCEMENT" CASCADE CONSTRAINTS;
CREATE TABLE "ANNOUNCEMENT" (
    "ANNOUNC_ID" NUMBER PRIMARY KEY,                    -- 공지사항 ID
    "BOARD_ID" NUMBER NOT NULL,                        -- 게시판 ID
    "USER_ID" VARCHAR2(30) NOT NULL,                   -- 작성자 ID
    "AUTH_ID" NUMBER NOT NULL,                         -- 권한 ID
    "TITLE" VARCHAR2(300) NOT NULL,                    -- 제목
    "CONTENT" CLOB NOT NULL,                           -- 내용
    "CREATED_DATE" DATE DEFAULT SYSDATE NOT NULL,      -- 생성 날짜
    FOREIGN KEY ("BOARD_ID") REFERENCES "BOARD"("BOARD_ID") 
        ON DELETE CASCADE,
    FOREIGN KEY ("USER_ID") REFERENCES "MEMBER"("USER_ID") 
        ON DELETE CASCADE,
    FOREIGN KEY ("AUTH_ID") REFERENCES "AUTHORITY"("AUTH_ID") 
        ON DELETE CASCADE
);
-- SEQUENCE 생성 (자동 증가 ID를 위한)
CREATE SEQUENCE ANNOUNCEMENT_SEQ 
START WITH 1 
INCREMENT BY 1 
NOCACHE 
NOCYCLE;
-- 트리거 생성 (ID 자동 증가)
CREATE OR REPLACE TRIGGER ANNOUNCEMENT_ID_TRIGGER
BEFORE INSERT ON "ANNOUNCEMENT"
FOR EACH ROW
BEGIN
    :NEW."ANNOUNC_ID" := ANNOUNCEMENT_SEQ.NEXTVAL;
END;

-- FAQ Table
CREATE TABLE FAQ (
    "FAQ_ID" NUMBER PRIMARY KEY, -- FAQ 아이디
    "BOARD_ID" NUMBER NOT NULL,
    "USER_ID" VARCHAR2(30) NOT NULL,
    "AUTH_ID" NUMBER NOT NULL,
    "TITLE" VARCHAR2(300) NOT NULL,
    "CONTENT" CLOB NOT NULL,
    "CREATED_DATE" DATE DEFAULT SYSDATE NOT NULL,      -- 생성 날짜
    FOREIGN KEY ("BOARD_ID") REFERENCES "BOARD"("BOARD_ID") 
        ON DELETE CASCADE,
    FOREIGN KEY ("USER_ID") REFERENCES "MEMBER"("USER_ID") 
        ON DELETE CASCADE,
    FOREIGN KEY ("AUTH_ID") REFERENCES "AUTHORITY"("AUTH_ID") 
        ON DELETE CASCADE
);
-- SEQUENCE 생성 (자동 증가 ID를 위한)
CREATE SEQUENCE FAQ_SEQ 
START WITH 1 
INCREMENT BY 1 
NOCACHE 
NOCYCLE;
-- 트리거 생성 (ID 자동 증가)
CREATE OR REPLACE TRIGGER FAQ_ID_TRIGGER
BEFORE INSERT ON "FAQ"
FOR EACH ROW
BEGIN
    :NEW."FAQ_ID" := FAQ_SEQ.NEXTVAL;
END;

-- QNA Table
CREATE TABLE QNA (
    "QNA_ID" NUMBER PRIMARY KEY, -- QnA 아이디
    "BOARD_ID" NUMBER NOT NULL, -- 게시판 아이디
    "USER_ID" VARCHAR2(30) NOT NULL, -- 작성자 아이디
    "AUTH_ID" NUMBER NOT NULL, -- 권한 아이디
    "TITLE" VARCHAR2(300) NOT NULL, -- 제목
    "CONTENT" CLOB NOT NULL, -- 본문 내용
    "ANSWER" CLOB, -- 답변 내용
    "PASSWORD" VARCHAR2(255),
    "IS_SECRET" NUMBER(1) DEFAULT 0 NOT NULL,     -- 비밀글 여부
    "CREATED_DATE" DATE DEFAULT SYSDATE NOT NULL, -- 생성 날짜
    FOREIGN KEY ("BOARD_ID") REFERENCES "BOARD"("BOARD_ID") 
        ON DELETE CASCADE,
    FOREIGN KEY ("USER_ID") REFERENCES "MEMBER"("USER_ID") 
        ON DELETE CASCADE,
    FOREIGN KEY ("AUTH_ID") REFERENCES "AUTHORITY"("AUTH_ID") 
        ON DELETE CASCADE
);
-- SEQUENCE 생성 (자동 증가 ID를 위한)
CREATE SEQUENCE QNA_SEQ 
START WITH 1 
INCREMENT BY 1 
NOCACHE 
NOCYCLE;
-- 트리거 생성 (ID 자동 증가)
CREATE OR REPLACE TRIGGER QNA_ID_TRIGGER
BEFORE INSERT ON "QNA"
FOR EACH ROW
BEGIN
    :NEW."QNA_ID" := QNA_SEQ.NEXTVAL;
END;

-- Category Table
CREATE TABLE "CATEGORY" (
    "CATEGORY_ID" NUMBER PRIMARY KEY, -- 카테고리 아이디
    "CATEGORY_NAME" VARCHAR2(30) NOT NULL -- 카테고리명
);
CREATE SEQUENCE SEQ_CATEGORY NOCACHE;


CREATE TABLE "PRODUCT" ( 
    "PRODUCT_ID" NUMBER PRIMARY KEY, -- 상품 아이디
    "USER_ID" VARCHAR2(30) NOT NULL,
    "CATEGORY_ID" NUMBER NOT NULL, -- 카테고리 아이디 (이 부분을 일치시켰습니다)
    "AUTH_ID" NUMBER NOT NULL, -- 권한 식별자
    "P_PRICE" NUMBER NOT NULL, -- 가격
    "P_NAME" VARCHAR2(300) NOT NULL, -- 상품명
    "P_STOCK" NUMBER NOT NULL, -- 재고
    "P_ENROLL" DATE NOT NULL, -- 등록일
    FOREIGN KEY ("USER_ID") REFERENCES "MEMBER"("USER_ID"),
    FOREIGN KEY ("AUTH_ID") REFERENCES "AUTHORITY"("AUTH_ID"), -- 관계 설정
    FOREIGN KEY ("CATEGORY_ID") REFERENCES "CATEGORY"("CATEGORY_ID") -- 관계 설정
);
CREATE SEQUENCE SEQ_PRODUCT NOCACHE;

-- Review Table
CREATE TABLE REVIEW (
    "REVIEW_ID" NUMBER PRIMARY KEY, -- 리뷰 아이디
    "PRODUCT_ID" NUMBER NOT NULL, -- 상품 참조
    "USER_ID" VARCHAR2(30) NOT NULL,
    "AUTH_ID" NUMBER NOT NULL,
    "TITLE" VARCHAR2(300) NOT NULL,
    "CONTENT" VARCHAR2(3000) NOT NULL,
    "DATE" DATE NOT NULL,
    "RATING" NUMBER NOT NULL, -- 평점
    FOREIGN KEY ("PRODUCT_ID") REFERENCES "PRODUCT"("PRODUCT_ID"),
    FOREIGN KEY ("USER_ID") REFERENCES "MEMBER"("USER_ID"),
    FOREIGN KEY ("AUTH_ID") REFERENCES "AUTHORITY"("AUTH_ID")
);
CREATE SEQUENCE SEQ_REVIEW NOCACHE;

-- Delivery Table
CREATE TABLE "DELIVERY" (
    "DELIVERY_ID" NUMBER PRIMARY KEY, 
    "ADRESSEE" VARCHAR2(300) NOT NULL,
    "ADDRESS" VARCHAR2(300) NOT NULL, 
    "PHONE" VARCHAR2(30) NOT NULL, 
    "DELIVERY_STATUS" VARCHAR2(100) NOT NULL
);
CREATE SEQUENCE SEQ_DELIVERY NOCACHE;

-- Order Table
CREATE TABLE "ORDER_TABLE" (
    "ORDER_ID" NUMBER PRIMARY KEY,         -- 주문 아이디
    "DELIVERY_ID" NUMBER NOT NULL,         -- 배송 아이디
    "USER_ID" VARCHAR2(30) NOT NULL,       -- 회원 아이디
    "PRODUCT_ID" NUMBER NOT NULL,          -- 상품 아이디
    "TOTAL_PRICE" NUMBER NOT NULL,         -- 총 가격
    "CARTSTATUS" CHAR(1) NOT NULL CHECK ("CARTSTATUS" IN ('Y', 'N')), -- 카트 상태 (Y/N)
    "PAYMENT_METHOD" VARCHAR2(30) NOT NULL, -- 결제 방법
    "ORDER_DATE" DATE NOT NULL,            -- 주문 날짜
    FOREIGN KEY ("USER_ID") REFERENCES "MEMBER"("USER_ID"), -- 회원 외래키
    FOREIGN KEY ("DELIVERY_ID") REFERENCES "DELIVERY"("DELIVERY_ID"), -- 배송 외래키
    FOREIGN KEY ("PRODUCT_ID") REFERENCES "PRODUCT"("PRODUCT_ID") -- 상품 외래키
);

CREATE SEQUENCE SEQ_ORDER_TABLE NOCACHE;

-- Payment Plan Table
CREATE TABLE "PAYMENT_PLAN" (
    "PP_ID" NUMBER PRIMARY KEY, -- 결제 계획 식별자
    "PP_NAME" VARCHAR2(30) NOT NULL -- 결제 방식
);
CREATE SEQUENCE SEQ_PAYMENT_PLAN NOCACHE;

-- Payment Card Table
CREATE TABLE "PAY_CARD" (
    "PC_ID" NUMBER PRIMARY KEY, -- 카드 결제 식별자
    "PP_ID" NUMBER NOT NULL, -- 결제 방식
    "CARD_TYPE" VARCHAR2(30) NOT NULL, -- 카드 타입
    "FIELD1" VARCHAR2(30),
    "FIELD2" VARCHAR2(30),
    "FIELD3" VARCHAR2(30),
    "FIELD4" VARCHAR2(30),
    FOREIGN KEY ("PP_ID") REFERENCES "PAYMENT_PLAN"("PP_ID") -- 관계 설정
);
CREATE SEQUENCE SEQ_PAYCARD NOCACHE;

-- Payment Bank Table
CREATE TABLE "PAY_BANK" (
    "BANK_ID" NUMBER PRIMARY KEY, -- 은행 결제 식별자
    "PP_ID" NUMBER NOT NULL, -- 결제 방식
    "BANK_NAME" VARCHAR2(100) NOT NULL, -- 은행명
    "FIELD5" VARCHAR2(30),
    "FIELD6" VARCHAR2(30),
    "FIELD7" VARCHAR2(30),
    FOREIGN KEY ("PP_ID") REFERENCES "PAYMENT_PLAN"("PP_ID") -- 관계 설정
);
CREATE SEQUENCE SEQ_PAYBANK NOCACHE;

-- Hardware Tables (CPU Example)
CREATE TABLE "CPU" (
    "CPU_ID" NUMBER PRIMARY KEY, -- CPU 아이디
    "CATEGORY_ID" NUMBER NOT NULL, -- 카테고리 아이디
    "MANUFACTURER" VARCHAR2(100) NOT NULL, -- 제조사
    "CORE_TYPES" NUMBER NOT NULL, -- 코어 종류
    "SOCKET" VARCHAR2(30) NOT NULL,
    "SUPPORTED_MEMORY_STANDARD" VARCHAR2(50) NOT NULL,
    FOREIGN KEY ("CATEGORY_ID") REFERENCES "CATEGORY"("CATEGORY_ID") -- 관계 설정
);
CREATE SEQUENCE SEQ_CPU NOCACHE;
-- SSD 테이블
CREATE TABLE "SSD" (
	"SSD_ID" NUMBER PRIMARY KEY,
    "CATEGORY_ID" NUMBER NOT NULL,
    "MANUFACTURER" VARCHAR(230) NOT NULL,
    "FORM_FACTOR" VARCHAR(230) NOT NULL,
    "CAPACITY" VARCHAR(230) NOT NULL,
    "INTERFACE" VARCHAR(230) NOT NULL,
    "PROTOCOL" VARCHAR(230) NOT NULL,
    FOREIGN KEY ("CATEGORY_ID") REFERENCES "CATEGORY"("CATEGORY_ID") -- 관계 설정
);
CREATE SEQUENCE SEQ_SSD NOCACHE;

-- 쿨러 테이블
CREATE TABLE "COOLER" (
	"COOLER_ID" NUMBER PRIMARY KEY,
    "CATEGORY_ID" NUMBER NOT NULL,
    "MANUFACTURER" VARCHAR(230) NOT NULL,
    "COOLING_METHOD" VARCHAR(230) NOT NULL,
    "WARRANTY_PERIOD" VARCHAR(230) NOT NULL,
    FOREIGN KEY ("CATEGORY_ID") REFERENCES "CATEGORY"("CATEGORY_ID") -- 관계 설정
);
CREATE SEQUENCE SEQ_COOLER NOCACHE;

-- 그래픽 카드 테이블
CREATE TABLE "GRAPHIC_CARD" (
	"GRAPHIC_CARD_ID" NUMBER PRIMARY KEY,
    "CATEGORY_ID" NUMBER NOT NULL,
    "MANUFACTURER" VARCHAR(230) NOT NULL,
    "CHIPSET_MANUFACTURER" VARCHAR(230) NOT NULL,
    "CHIPSET" VARCHAR(230) NOT NULL,
    "VGA_LENGTH" NUMBER NOT NULL,
    FOREIGN KEY ("CATEGORY_ID") REFERENCES "CATEGORY"("CATEGORY_ID") -- 관계 설정
);
CREATE SEQUENCE SEQ_GRAPHIC_CARD NOCACHE;

-- HDD 테이블
CREATE TABLE "HDD" (
	"HDD_ID" NUMBER PRIMARY KEY,
    "CATEGORY_ID" NUMBER NOT NULL,
    "MANUFACTURER" VARCHAR(230) NOT NULL,
    "PRODUCT_CLASSIFICATION" VARCHAR(230) NOT NULL,
    "DISK_SIZE" VARCHAR(230) NOT NULL,
    "CAPACITY" VARCHAR(230) NOT NULL,
    "INTERFACE" VARCHAR(230) NOT NULL,
    FOREIGN KEY ("CATEGORY_ID") REFERENCES "CATEGORY"("CATEGORY_ID") -- 관계 설정
);
CREATE SEQUENCE SEQ_HDD NOCACHE;

-- POWER 테이블
CREATE TABLE "POWER" (
	"POWER_ID" NUMBER PRIMARY KEY,
    "CATEGORY_ID" NUMBER NOT NULL,
    "MANUFACTURER" VARCHAR(230) NOT NULL,
    "RATED_OUTPUT" VARCHAR(230) NOT NULL,
    "EFFICIENCY_CERTIFICATION" VARCHAR(230) NOT NULL,
    "PSU_STANDARD" VARCHAR(230) NOT NULL,
    FOREIGN KEY ("CATEGORY_ID") REFERENCES "CATEGORY"("CATEGORY_ID") -- 관계 설정
);
CREATE SEQUENCE SEQ_POWER NOCACHE;

-- RAM 테이블
CREATE TABLE "RAM" (
	"RAM_ID" NUMBER PRIMARY KEY,
    "CATEGORY_ID" NUMBER NOT NULL,
    "MANUFACTURER" VARCHAR(230) NOT NULL,
    "PRODUCT_CLASSIFICATION" VARCHAR(230) NOT NULL,
    "CAPACITY" VARCHAR(230) NOT NULL,
    "OPERATING_CLOCK" VARCHAR(230) NOT NULL,
    FOREIGN KEY ("CATEGORY_ID") REFERENCES "CATEGORY"("CATEGORY_ID") -- 관계 설정
);
CREATE SEQUENCE SEQ_RAM NOCACHE;
-- MAINBOARD 테이블
CREATE TABLE MAINBOARD (
	"MAINBOARD_ID" NUMBER PRIMARY KEY,
    "CATEGORY_ID" NUMBER NOT NULL,
    "PRODUCT_CLASSIFICATION" VARCHAR(230) NOT NULL,
    "MANUFACTURER" VARCHAR(230) NOT NULL,
    "SOCKET" VARCHAR(230) NOT NULL,
    "DETAILED_CHIPSET" VARCHAR(230) NOT NULL,
    "FORM_FACTOR" VARCHAR(230) NOT NULL,
    "VCORE_OUTPUT_TOTAL" VARCHAR(230) NOT NULL,
    "SUPPORTED_MEMORY_STANDARD" VARCHAR2(50) NOT NULL,
    FOREIGN KEY ("CATEGORY_ID") REFERENCES "CATEGORY"("CATEGORY_ID") -- 관계 설정
);
CREATE SEQUENCE SEQ_MAINBOARD NOCACHE;
-- CASE 테이블
CREATE TABLE "CASE" (
	"CASE" NUMBER PRIMARY KEY,
    "CATEGORY_ID" NUMBER NOT NULL,
    "MANUFACTURER" VARCHAR(230) NOT NULL,
    "PRODUCT_CLASSIFICATION" VARCHAR(230) NOT NULL,
    "CASE_SIZE" VARCHAR(230) NOT NULL,
    "POWER_SUPPLY_STANDARD" VARCHAR(230) NOT NULL,
    "SUPPORTED_BOARD_STANDARD" VARCHAR(230) NOT NULL,
    "BAY_13_3CM" VARCHAR(230) NOT NULL,
    "BAY_8_9CM" VARCHAR(230) NOT NULL,
    "VGA_LENGTH" NUMBER NOT NULL,
    FOREIGN KEY ("CATEGORY_ID") REFERENCES "CATEGORY"("CATEGORY_ID") -- 관계 설정
);
CREATE SEQUENCE SEQ_CASE NOCACHE;
